import { ReloadIcon } from '@radix-ui/react-icons';
import {
  ArrowRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  FileText,
  GraduationCap,
  LogOut,
  MailCheck,
  MailQuestion,
  Minus,
  Moon,
  MoreHorizontal,
  Pencil,
  Play,
  Plus,
  PlusCircle,
  Save,
  Send,
  SendHorizonal,
  Settings,
  Share,
  Sun,
  Trash,
  Users,
  X,
  XCircle,
} from 'lucide-react';

export const Icons = {
  loading: ReloadIcon,
  settings: Settings,
  chevronDown: ChevronDown,
  logout: LogOut,
  graduationCap: GraduationCap,
  plusCircle: PlusCircle,
  trash: Trash,
  x: X,
  fileText: FileText,
  plus: Plus,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  pencil: Pencil,
  save: Save,
  sun: Sun,
  moon: Moon,
  arrowRight: ArrowRight,
  play: Play,
  check: Check,
  moreHorizontal: MoreHorizontal,
  xCircle: XCircle,
  send: Send,
  users: Users,
  minus: Minus,
  share: Share,
  sendHorizonal: SendHorizonal,
  mailCheck: MailCheck,
  mailQuestion: MailQuestion,
};
